name: cdb_mobile
description: CDB Mobile Banking Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.11+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_bloc: ^7.0.1
  intl: ^0.17.0
  get_it:
  equatable: ^2.0.3
  dartz: ^0.9.2
  flutter_svg: ^0.22.0
  dio: ^4.0.0
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.3
  camera: ^0.8.1+3
  image_cropper: ^1.4.1
  image_picker: ^0.8.1+3
  connectivity: ^3.0.6
  shared_preferences: ^2.0.7
  flutter_local_notifications: ^5.0.0+4
  flutter_secure_storage: ^4.2.1
  installer_info: ^0.3.0
  trust_fall: ^1.0.4
  pointycastle: ^3.1.3
  encrypt: ^5.0.0
  hex: ^0.2.0
  xor: ^0.2.2
  http_certificate_pinning: ^2.0.0
  date_format: ^2.0.2
  flutter_udid: ^2.0.0
  uuid: ^3.0.4
  device_info: ^2.0.2
  wifi: ^0.1.5
  geolocator: ^7.3.1
  package_info: ^2.0.2
  flutter_screenutil: ^5.0.0+2
  firebase_analytics: ^8.2.0
  percent_indicator: ^3.0.1
  provider: ^6.0.0
  local_auth: ^1.1.6
  extended_masked_text: ^2.3.1
  lottie: ^1.1.0
  simple_animations: ^3.1.1
  flutter_keyboard_visibility: ^5.0.3
  permission_handler: ^8.1.6
  otp_count_down: ^1.0.6
  url_launcher: ^6.0.10
  flutter_html: ^2.1.5
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.0.0
  super_tooltip: ^1.0.1
  simple_tooltip: ^1.0.0
  list_tile_switch: ^1.0.0
  qr_code_scanner: ^0.4.0
  sentry_flutter: ^5.0.0
  flutter_switch: ^0.3.2

  #Huawei Dependencies
  huawei_push: ^6.3.0+304

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - locales/
    - animations/
    - images/pngs/
    - images/svgs/
  fonts:
    - family: PublicSans
      fonts:
        - asset: fonts/PublicSans-Black.ttf
          weight: 900
        - asset: fonts/PublicSans-Blackitalic.ttf
          style: italic
          weight: 900
        - asset: fonts/PublicSans-Bold.ttf
          weight: 700
        - asset: fonts/PublicSans-Bolditalic.ttf
          style: italic
          weight: 700
        - asset: fonts/PublicSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/PublicSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/PublicSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/PublicSans-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/PublicSans-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/PublicSans-Light.ttf
          weight: 300
        - asset: fonts/PublicSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/PublicSans-Medium.ttf
          weight: 500
        - asset: fonts/PublicSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/PublicSans-Regular.ttf
          weight: 400
        - asset: fonts/PublicSans-SemiBold.ttf
          weight: 600
        - asset: fonts/PublicSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/PublicSans-Thin.ttf
          weight: 100
        - asset: fonts/PublicSans-ThinItalic.ttf
          style: italic
          weight: 100
    - family: CDBIcons
      fonts:
        - asset: fonts/CDBIcons.ttf