enum Flavor { DEV, UAT, QA, LIVE }
enum AlertType { SUCCESS, FAIL }
enum DeviceOS { ANDROID, HUAWEI }
enum SecurityFailureType { ADB, ROOT, EMU, SECURE, SOURCE }
enum KYCStep {
  PERSONALINFO,
  CONTACTINFO,
  EMPDETAILS,
  OTHERINFO,
  DOCUMENTVERIFY,
  SCHEDULEVERIFY,
  REVIEW,
  TNC,
  INTERSTEDPROD,
  SECURITYQ,
  CREATEUSER,
  BIOMETRIC
}
enum StepperState { COMPLETED, PENDING, INACTIVE }
enum ButtonStatus { ENABLE, DISABLE }
enum IDType { SELFIE, ID_FRONT, ID_BACK, BILLING_PROOF }
enum EmptyViewType { MYFAVOURITE, RECENTTRANSACTIONS, BILLER_LIST, ACCOUNT, NO_RESULTS, NO_ONGOING_SCHEDULES, NO_UPCOMING_SCHEDULES, NO_COMPLETED_SCHEDULES, NO_DELETED_SCHEDULES }
enum FTType { SAVED, UNSAVED, SCHEDULED }
enum HttpMethods { POST, PUT, DELETE }
